runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /front
  static_dir: front

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: 2.7.11

includes:
- cloudinary.yaml
